services:
  #backend
  smart-brain-backend:
    container_name: backend
    build: ./
    command: npm run start:dev
    working_dir: /usr/src/smart-brain-backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-backend
    environment: 
      - NODE_ENV=development
  
  #postgres database
  postgres:
      build: ./postgres/
      env_file: 
        - ./postgres.env
      ports: 
        - "5432:5432"